project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Social Issue: Flight Delay"
  author:
    - Xinyan Li (xl3469)
    - Shiqi Liu (sl5661)
  repo-url: https://github.com/Shiqi-Liu-Eric/EDAV_Final_Project.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: minty
    code-fold: true