# Conclusion

At the beginning of this project, we, as international students, tried to investigate the behind or deterministic factors for the flight delays. As we continue analyzing the data sets, we find out that weather conditions and seasonal differences play significant roles in influencing delays. For weather conditions, rainy and cloudy conditions hugely impact flight departure times. For seasonal differences, summer time, like August, tends to have more variability and higher average delay times. One of the possible reasons behind this is that the demand for traveling is higher compared with the wintertime. Differences in New York departure airports and destinations suggest that seasonal preferences for flights should exist. However, our study is limited by only paying attention to a subset of variables and simplified data sets. This might lead to ignoring complicated interactions behind the appearance of flight delays, such as flight scheduling and socioeconomic factors. In the future, we can include more airline-specific analysis data, accurate weather data, flight network information, and passenger demand. With those explorations, the future project could be more comprehensive. Lessons learned from this project are that departure delay times are important because of the strong correlation with arrival delay times. Also, seasonal differences and weather conditions play a crucial role in flight delays. The interplay of weather and seasons is the major indicator of why the flights cannot depart or arrive on time. Even though airports are all in New York, it does not mean that they have equal flight demands. For example, JFK Airport has a higher passenger volume than EWR Airport, so this explains why JFK Airport has a higher delay frequency than EWR Airport. 